/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

export type RawVecInput = { ptr: any; cap: BigNumberish };

export type RawVecOutput = { ptr: any; cap: BN };

export type VecInput = { buf: RawVecInput; len: BigNumberish };

export type VecOutput = { buf: RawVecOutput; len: BN };

interface HyperlaneMailboxAbiInterface extends Interface {
  functions: {
    count: FunctionFragment;
    dispatch: FunctionFragment;
    latest_checkpoint: FunctionFragment;
    root: FunctionFragment;
  };

  encodeFunctionData(functionFragment: "count", values?: undefined): Uint8Array;
  encodeFunctionData(
    functionFragment: "dispatch",
    values: [BigNumberish, string, VecInput]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "latest_checkpoint",
    values?: undefined
  ): Uint8Array;
  encodeFunctionData(functionFragment: "root", values?: undefined): Uint8Array;

  decodeFunctionData(functionFragment: "count", data: BytesLike): DecodedValue;
  decodeFunctionData(
    functionFragment: "dispatch",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "latest_checkpoint",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(functionFragment: "root", data: BytesLike): DecodedValue;
}

export class HyperlaneMailboxAbi extends Contract {
  interface: HyperlaneMailboxAbiInterface;
  functions: {
    count: InvokeFunction<[], number>;

    dispatch: InvokeFunction<
      [
        destination_domain: BigNumberish,
        recipient: string,
        message_body: VecInput
      ],
      string
    >;

    latest_checkpoint: InvokeFunction<[], [string, number]>;

    root: InvokeFunction<[], string>;
  };
}
