/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HyperlaneMailboxAbi } from "./HyperlaneMailboxAbi";

export { HyperlaneMailboxAbi__factory } from "./factories/HyperlaneMailboxAbi__factory";
