[project]
authors = ["Trevor Porter", "Yorke Rhodes"]
entry = "main.sw"
license = "Apache-2.0"
name = "hyperlane-mailbox"

[dependencies]
hyperlane_interfaces = { path = "../hyperlane-interfaces" }
hyperlane_message = { path = "../hyperlane-message" }
merkle = { path = "../merkle" }
ownership = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.8.0" }
pause = { path = "../pause" }
reentrancy = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.8.0" }
std_lib_extended = { path = "../std-lib-extended" }
