[project]
authors = ["Trevor Porter", "Yorke Rhodes"]
entry = "main.sw"
license = "Apache-2.0"
name = "hyperlane-mailbox"

[dependencies]
hyperlane_message = { path = "../hyperlane-message" }
merkle = { path = "../merkle" }
multisig = { path = "../multisig-ism" }
