[workspace]

members = [
    "hyperlane-mailbox",
    "hyperlane-message-test",
    "merkle-test",
    "test-utils"
]

[workspace.dependencies]
ethers = { git = "https://github.com/hyperlane-xyz/ethers-rs", tag = "2022-12-05-01", default-features = false, features = ['legacy'] }
fuels = { version = "0.37", features = ["fuel-core-lib"] }
hyperlane-core = { git = "https://github.com/hyperlane-xyz/hyperlane-monorepo", rev = "253e5f8" }
tokio = { version = "1.12", features = ["rt", "macros"] }
