[workspace]

members = [
  "contracts/bytes-extended",
  "contracts/hyperlane-interfaces",
  "contracts/hyperlane-message",
  "contracts/hyperlane-message-test",
  "contracts/merkle",
  "contracts/merkle-test",
  "contracts/hyperlane-mailbox",
  "contracts/hyperlane-ism-test",
  "contracts/hyperlane-msg-recipient-test",
  "contracts/interchain-gas-paymaster",
  "contracts/std-lib-extended",
  "contracts/storage-gas-oracle",
]
