[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "interchain-gas-paymaster"

[dependencies]
hyperlane_interfaces = { path = "../../hyperlane-interfaces" }
ownership = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.8.0" }
std_lib_extended = { path = "../../std-lib-extended" }
