[package]
name = "hyperlane-message-test"
description = "A cargo-generate template for Rust + Sway integration testing."
version = "0.1.0"
edition = "2021"
authors = ["Trevor Porter <trkporter@ucdavis.edu>"]
license = "Apache-2.0"

[dev-dependencies]
ethers = { git = "https://github.com/abacus-network/ethers-rs", tag = "2022-10-28-01", default-features = false, features = ['legacy'] }
fuels = { version = "0.31", features = ["fuel-core-lib"] }
hex = "0.4.3"
hyperlane-core = { git = "https://github.com/hyperlane-xyz/hyperlane-monorepo", branch = "main" }
tokio = { version = "1.12", features = ["rt", "macros"] }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
