[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "storage-gas-oracle"

[dependencies]
hyperlane_interfaces = { path = "../../hyperlane-interfaces" }
ownership = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.12.0" }
