[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "storage-gas-oracle"

[dependencies]
hyperlane_interfaces = { path = "../hyperlane-interfaces" }
ownership = { path = "../ownership" }
