[project]
authors = ["Yorke Rhodes"]
entry = "main.sw"
license = "Apache-2.0"
name = "multisig_ism"

[dependencies]
hyperlane_interfaces = { path = "../hyperlane-interfaces" }
hyperlane_message = { path = "../hyperlane-message" }
merkle = { path = "../merkle" }
multisig_ism_metadata = { path = "../multisig-ism-metadata" }
ownership = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.12.0" }
std_lib_extended = { path = "../std-lib-extended" }
