[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "overhead-igp"

[dependencies]
hyperlane_interfaces = { path = "../../hyperlane-interfaces" }
ownership = { git = "https://github.com/fuellabs/sway-libs", rev = "82a1eea" }
