[project]
authors = ["Yorke Rhodes", "Trevor Porter"]
entry = "lib.sw"
license = "Apache-2.0"
name = "hyperlane_interfaces"

[dependencies]
hyperlane_message = { path = "../hyperlane-message" }
ownership = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.9.0" }
