[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "interchain-gas-paymaster"

[dependencies]
hyperlane_interfaces = { path = "../hyperlane-interfaces" }
ownership = { path = "../ownership" }
std_lib_extended = { path = "../std-lib-extended" }
