[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "hyperlane_message"

[dependencies]
bytes_extended = { path = "../bytes-extended" }
# Temporary to get access to the upstream `Bytes` that has not yet been released.
std = { git = "https://github.com/fuellabs/sway", branch = "master", com = "783044d87db960695a765f12ba025435b4408ef3" }
