name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always
  FUELUP: /opt/hostedtoolcache/FuelLabs/fuelup/latest/linux-x64/fuelup-0.15.1-x86_64-unknown-linux-gnu
  FORC: $HOME/.fuelup/bin/forc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: install fuelup
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: FuelLabs/fuelup
      - run: $FUELUP toolchain install latest
      - run: $FORC build
      - run: $FORC test
      - run: cargo build
      - run: cargo test
