name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://fuellabs.github.io/fuelup/fuelup-init.sh | sh -s -- --no-modify-path
          export PATH="${HOME}/.fuelup/bin:${PATH}"
          fuelup toolchain install latest

      - run: cargo build
      - run: forc build
      - uses: actions/upload-artifact@v3
        with:
          path: |
            target/
            out/
            $HOME/.cargo/
            $HOME/.fuelup/

  cargo-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: target/
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

  forc-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: |
            $HOME/.fuelup/
            out/
      - run: forc test
      - run: forc fmt -- --check
