name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: install fuelup
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: FuelLabs/fuelup

      - run: $HOME/.fuelup/bin/forc build
      - run: $HOME/.fuelup/bin/forc test
      - run: cargo build
      - run: cargo test
