name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Use https for git commands
        run: "git config --global url.https://github.com/.insteadOf git@github.com:"
      - name: install fuelup
        run: |
          # Using -L to deal with redirects, see https://github.com/FuelLabs/sway/issues/4309
          curl -L https://fuellabs.github.io/fuelup/fuelup-init.sh | sh -s -- --no-modify-path
          echo "$HOME/.fuelup/bin" >> $GITHUB_PATH
      - run: forc build
      - run: forc test
      - run: cargo build
      - run: cargo test
