[project]
authors = ["Yorke Rhodes"]
entry = "main.sw"
license = "Apache-2.0"
name = "multisig_ism"

[dependencies]
merkle = { path = "../merkle" }
multisig_ism_metadata = { path = "../multisig-ism-metadata" }
hyperlane_message = { path = "../hyperlane-message" }
bytes_extended = { path = "../bytes-extended" }
