[project]
authors = ["Yorke Rhodes"]
entry = "main.sw"
license = "Apache-2.0"
name = "multisig-ism"

[dependencies]
merkle = { path = "../merkle" }
hyperlane_message = { path = "../hyperlane-message" }
