[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "validator-announce"

[dependencies]
bytes_extended = { path = "../bytes-extended" }
storagemapvec = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.7.1" }
